---
title: "EIH prediction using AI approaches"
author: "Félix Boudry"
date: "`r Sys.Date()`"
documentclass: article
classoption: oneside
lang: en-US
output:
  html_document:
    toc: yes
    number_section: yes
    fig_caption: yes
    keep_md: yes
params:
  new_models:
    label: "Compute new models?"
    value: true
  seed:
    label: "Seed:"
    value: 42
    input: numeric
  data:
    label: "Input dataset:"
    value: none
    input: file   
  data_list:
    label: "List of files to import:"
    value: none
    input: text
  data_folder:
    label: "Path to multiple data sets folder:"
    value: "./Data"
    input: text
  predict_label:
    label: "Feature to predict:"
    value: c("eih")
    input: text
  excluded_variables:
    label: "Features to exclude from clustering and training:"
    value: c("saturation_rest", "saturation_end", "saturation_delta", "subject", "eih_severity")
    input: text
---

```{r Setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  message = FALSE,
  warning = FALSE
)
reticulate::use_virtualenv(virtualenv = "EIH")
project_seed <- params$seed
set.seed(seed = project_seed)

# Import libraries
source("./Scripts/Functions.R")
library(data.table)
library(tidyverse)
library(factoextra)
library(clusplus) # https://github.com/pablo14/clusplus
library(caret)
library(gbm)
library(lightgbm)
library(reticulate)
library(shapviz)
library(magrittr)
library(gridExtra)
library(psych)
library(fs)
library(tools)
library(CatEncoders)

# Create a folder to save results
analysis_date <- format(Sys.time(), "%Y-%m-%d_%H.%M.%S")
dir_create(path = paste0("Output/", analysis_date))

## Parsing and evaluating strings used as parameters to be used as code
excluded_variables <-
  eval_knit_param(params$excluded_variables)
predict_label <-
  eval_knit_param(params$predict_label)

## Manual parameters for the analysis
cluster_number <- 2
cluster_number_names <- "two"
ml_split <- 0.8
optuna_trials <- 25000
lgbm_rounds <- 45
xgboost_rounds <- 45
```

```{r Import & scripts, include=FALSE}
# Import selected data set creating imported_data_names and imported_data
data_read()

# Create environments (one per data set, used for results storage)
my_envs <- lapply(X = imported_data_names, FUN = \(df_name) {
  my_name <- df_name
  df_name <- paste0(df_name, "_env") %>%
    assign(value = new.env())
  assign(x = "name", value = my_name, envir = df_name)
  return(df_name)
}) %>%
  `names<-`(value = imported_data_names)

# Source scripts for analysis
for (df_name in imported_data_names) {
  dir_create(path = paste0("Models/", df_name))
  env_name <- as.character(df_name)
  no_num_colnames <- # Columns that will be encoded
    dplyr::select_if(imported_data[[df_name]], negate(is.numeric)) %>%
    colnames()
  antrop_data <- imported_data[[df_name]][, c("age",
                                              "height",
                                              "weight",
                                              "train_years",
                                              "train_volume")]
  analysis_data <- imported_data[[df_name]] %>%
    df_encode() %$%
    encoded_data %>%
    clean_dataset() %>%
    round(digits = 4)
  names(convert_dic) <-
    no_num_colnames # Naming encoding list elements
  compute_env <- my_envs[[df_name]]
  source("./Scripts/Unsupervised.R", local = compute_env)
  source("./Scripts/Supervised.R", local = compute_env)
}
```

# EIH prediction

This report shows the classifications achieved using various methods to detect
EIH subjects.

```{r Results, echo=FALSE, results='asis'}
for (my_env in my_envs) {
  cat(knitr::knit_child('Result_template.Rmd', envir = my_env, quiet = TRUE))
}
```

# Knitting parameters

The following parameters were used as input to create this report:

```{r Infos}
params %>% do.call(what = rbind, args = .) %>% my_table()
```

```{r End_tasks, include=FALSE}
result_save()
```
