---
title: "Result_template"
author: "Félix Boudry"
date: "`r Sys.Date()`"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# `r paste(my_env$name)`

## Material and methods

### Subjects

```{r}
analysis_data <- as.data.frame(analysis_data)
describe(x = analysis_data[c("age",
                             "height",
                             "weight",
                             "train_years",
                             "train_volume",
                             "vo2_maximum")] , na.rm = T) %>%
  round() %>%
  select(c("mean", "sd", "median", "min", "max")) %>%
  my_table(
    caption = paste0(
      "<center><strong>Anthropological values (n = ",
      nrow(analysis_data) ,
      ")</center></strong>"
    )
  )
```

### Parameters

```{r}

```

## Results

### Unsupervised learning

#### K-means clustering

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
kclust_graph %>% walk(print)
kclust_coord %>% walk(print)

confusion_list_export("^kclust")
```

#### Hierarchical bottom-up clustering

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
hclust_bu_graph %>% walk(print)
confusion_list_export("^hclust_bu")
```

#### Hierarchical top-down clustering

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
hclust_td_graph %>% walk(print)
confusion_list_export("^hclust_td")
```

<!-- #### DBSCAN clustering -->

<!-- ```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'} -->
<!-- # rmd_plot2("^dbscan") -->
<!-- ``` -->

<!-- #### OPTICS clustering -->
<!-- ```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'} -->
<!-- # rmd_plot2("^optics") -->
<!-- ``` -->

### Supervised learning

#### LightGBM

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
accuracy_status
best_accuracy_status
best_params_status
conf_matrix_status
t(as.data.frame(lgbm_model_status$params[c(
  "boosting",
  "lambda_l1",
  "lambda_l2",
  "num_leaves",
  "max_depth",
  "feature_fraction",
  "bagging_fraction",
  "bagging_freq",
  "learning_rate"
)])) %>% my_table()
lgbm_importance_plot_status %>%
  lgb.plot.importance()
lgbm_importance_plot_status %>%
  lgb.plot.interpretation()
lgbm_plot_status %>%
  walk(print)

accuracy_intensity
best_accuracy_intensity
best_params_intensity
conf_matrix_intensity
t(as.data.frame(lgbm_model_intensity$params[c(
  "boosting",
  "lambda_l1",
  "lambda_l2",
  "num_leaves",
  "max_depth",
  "feature_fraction",
  "bagging_fraction",
  "bagging_freq",
  "learning_rate"
)])) %>% my_table()
lgbm_importance_plot_intensity %>%
  lgb.plot.importance()
lgbm_importance_plot_intensity %>%
  lgb.plot.interpretation()
lgbm_plot_intensity %>%
  walk(print)
```
