# Informations ------------------------------------------------------------
# Title: Compute.R
# Author: Félix Boudry
# Contact: <felix.boudry@univ-perp.fr>
# License: Private
# Description: Compute needed data and format them

# Configuration -----------------------------------------------------------

## Libraries --------------------------------------------------------------
## List of used libraries.
require(tidyverse)
require(FactoMineR)
require(missMDA)

# Environment -------------------------------------------------------------
# Load environment generated by previous script
rm(list = setdiff(x = ls(), y = lsf.str())) # Clean environment
load(file = "./Environments/import.RData") # Load environment

# Select columns ----------------------------------------------------------
# Select only columns present in all data frames
my_data$all <- lapply(X = my_data$all, FUN = colnames) %>%
  Reduce(f = intersect) %>%
  lapply(X = my_data$all, FUN = "[", .)
my_colnames <- colnames(my_data$all[[1]])

# Clean data --------------------------------------------------------------
# remove NA only rows and outliers in raw data
my_data$all <-
  lapply(
    X = my_data$all,
    FUN = function(my_dataframe)
      filter(.data = my_dataframe,
             rowSums(x = is.na(x = my_dataframe)) != ncol(x = my_dataframe))
  ) %>%
  remove_outliers()

# Summary absolute --------------------------------------------------------
# Summarizing all data frames into one
my_summary <- mapply(
  FUN = function(df_input, name_input)
    dplyr::summarise(df_input, across(
      # Compute .fns for each column
      .cols = everything(),
      # Columns to compute
      .fns = list(
        # Functions to apply on columns
        mean = mean,
        max = max,
        min = min,
        median = median
      ),
      na.rm = TRUE
    )) %>%
    cbind("subject" = name_input),
  df_input = my_data$all,
  name_input = names(my_data$all)
) %>%
  t() %>%
  as.data.frame() %>%
  unnest(cols = colnames(x = .)) %>%
  merge(y = my_data$infos, by = "subject", all = TRUE)

# Summary relative --------------------------------------------------------
# Transform mean and min columns to relatives max values
my_summary_relative <- my_summary %>% # Copy summary
  compute_relative()

# PCA ---------------------------------------------------------------------
# Compute a PCA summary for analyzed data
PCA_summary <- lapply(my_data$all, imputePCA) %>%
  lapply(FUN = as.data.frame) %>%
  lapply(FUN = select, contains(my_colnames)) %>%
  lapply(FUN = PCA, graph = FALSE) %>%
  lapply(FUN = "[", "eig") %>%
  lapply(FUN = unlist) %>%
  do.call(what = rbind, args = .) %>%
  as.data.frame() %>%
  rownames_to_column(.data = ., var = "subject")

# Cleaning ----------------------------------------------------------------
# Removes outliers in summaries
my_summaries <-
  lst(my_summary, my_summary_relative, PCA_summary) %>%
  `names<-`(value = c("summary", "relative_summary", "PCA_summary"))

# Data structure ----------------------------------------------------------
# Structuring data in vectors
my_data <- # Append summary in "my_data"
  append(x = my_data,
         values = lst(my_summaries)) %>%
  `names<-`(c(names(x = my_data),
              "summaries"))

# Remove variables not containing "my_data" & my_data_frame
rm(list = setdiff(x = ls(), y = c(lsf.str(), ls(pattern = "my_data"))))

# Export data -------------------------------------------------------------
# Save environment to avoid recomputing
save.image(file = "./Environments/compute.RData")
