# Informations ------------------------------------------------------------

# Title: Compute.R
# Author: Félix Boudry
# Contact: <felix.boudry@laposte.net>
# License: Private
# Description: Compute needed data and format them

# Configuration -----------------------------------------------------------

## Libraries --------------------------------------------------------------
## List of used libraries.
require(plyr)
require(dplyr)
require(tibble)
require(CatEncoders)

# Environment -------------------------------------------------------------
# Load environment generated by previous script
rm(list = ls()) # Clean environment
load(file = "./Environments/import.RData") # Load environment

# Select columns ----------------------------------------------------------
# Select only columns present in all data frames
my_colnames <- lapply(X = my_data$all, FUN = colnames) %>%
  Reduce(f = intersect, x = .)
my_data$all <- lapply(X = my_data$all, FUN = "[", my_colnames)

# Clean data --------------------------------------------------------------
# remove NA only rows
my_data$all <-
  lapply(
    X = my_data$all,
    FUN = function(my_dataframe)
      filter(.data = my_dataframe,
             rowSums(x = is.na(x = my_dataframe)) != ncol(x = my_dataframe))
  )

# Remove outliers ---------------------------------------------------------
remove_outliers <-
  FALSE # Chose to keep or remove outliers, may loose accuracy
if (remove_outliers) {
  my_data$all <-
    lapply(
      X = my_data$all,
      FUN = function(my_dataframe)
        lapply(
          X = my_dataframe,
          FUN = function(my_col)
            lapply(
              X = my_col,
              FUN = function(my_value)
                ifelse(
                  test = my_value %in% boxplot.stats(my_col)$out,
                  yes = NA,
                  no = my_value
                )
            )
        )
    )
  my_data$all <-
    lapply(
      X = my_data$all,
      FUN = function(my_dataframe)
        data.frame(sapply(X = my_dataframe, FUN = c))
    )
  my_data$all <-
    lapply(
      X = my_data$all,
      FUN = function(x)
        lapply(X = x, FUN = as.numeric)
    ) %>%
    lapply(FUN = as.data.frame)
}

# Summarize ---------------------------------------------------------------
# Summarizing all data frames into one

## Compute ----------------------------------------------------------------
tmp_summary <- # Compute data for initial data frame
  dplyr::summarise(# Summarise a dataframe
    .data = my_data$all[[1]],
    across(
      # Compute .fns for each column
      .cols = everything(),
      # Columns to compute
      .fns = list(
        # Functions to apply on columns
        mean = mean,
        max = max,
        min = min,
        median = median
      ),
      na.rm = TRUE
    ))

my_summary <- tmp_summary # Creating dataframe to merge in loop
i <- 1
for (my_data_frame in my_data$all) {
  # Summarise each dataframe in list
  tmp_summary <- # Summarise a dataframe
    dplyr::summarise(.data = my_data_frame, across(
      # Compute .fns for each column
      .cols = everything(),
      # Columns to compute
      .fns = list(
        # Functions to apply on columns
        mean = mean,
        max = max,
        min = min,
        median = median
      ),
      na.rm = TRUE
    ))
  tmp_summary["sujet"] <- # Add "sujet" column with dataframe name
    sub(pattern = "\\.xlsx",
        # Remove extension
        replacement = "",
        names(my_data$all[i]))
  i <- i + 1
  my_summary <-
    merge(x = my_summary, y = tmp_summary, all = TRUE) # Append to summary
}

## Cleaning ---------------------------------------------------------------
## Set unused features
excluded_variables <- # Variables to remove from training data set
  c(
    "saturation_repos",
    "saturation_fin",
    "delta_saturation",
    "study_name",
    "test",
    "data_type",
    "type",
    "activity",
    "altitude",
    "environment",
    "intensity"
  )
## Set all unknown to NA's
my_summary <- # Replace "-Inf" with NAs
  mutate_all(.tbl = my_summary, ~ replace(., . == c("-Inf", "Inf"), NA))
my_summary <- # Remove NA only rows
  filter(.data = my_summary,
         rowSums(x = is.na(x = my_summary)) != ncol(x = my_summary)) %>%
  select_if(.tbl = ., # Remove columns on condition
            .predicate = colSums(x = is.na(x = my_summary)) < 5)
my_summary <- # Add informations to summary
  merge(
    x = my_summary,
    y = select(.data = my_data$infos, -excluded_variables),
    by = "sujet",
    all = TRUE
  )
## Put labels in separated data frames
my_labels <-
  select(.data = my_summary, c("sujet", "eih", "eih_severity"))
my_summary <- select(.data = my_summary, -c("eih", "eih_severity"))
## Labeling categorical variables
my_label_env_sex <- LabelEncoder.fit(my_summary$sexe)
my_summary$sexe <- transform(my_label_env_sex, my_summary$sexe)
my_label_env_sport <- LabelEncoder.fit(my_summary$sport)
my_summary$sport <- transform(my_label_env_sport, my_summary$sport)

# Relative values ---------------------------------------------------------
# Transform mean and min columns to relatives max values
my_summary_relative <- my_summary # Copy summary
maximum_columns <-
  grep(pattern = "max", x = colnames(x = my_summary_relative)) # List max columns

for (my_column in maximum_columns) {
  my_variable_name <- colnames(x = my_summary_relative[my_column]) %>%
    sub(pattern = "_max", replacement = "") # remove "_max" from column name
  max_colname <- paste0(my_variable_name, "_max")
  mean_colname <- paste0(my_variable_name, "_mean")
  min_colname <- paste0(my_variable_name, "_min")
  my_summary_relative[min_colname] <- # Compute minimum values as %
    100 * my_summary_relative[min_colname] / my_summary_relative[max_colname]
  my_summary_relative[mean_colname] <- # Compute mean values as %
    100 * my_summary_relative[mean_colname] / my_summary_relative[max_colname]
}

# Data structure ----------------------------------------------------------
# Structuring data in vectors
my_data <- # Append summary in "my_data"
  append(
    x = my_data,
    values = lst(my_summary, my_summary_relative, my_labels, my_label_env_sex, my_label_env_sport)
  ) %>%
  `names<-`(c(
    names(x = my_data),
    "summary",
    "summary_relative",
    "labels",
    "label_env_sex",
    "label_env_sport"
  ))

# Remove variables not containing "my_data" & my_data_frame
rm(list = setdiff(x = ls(), y = ls(pattern = "my_data")), my_data_frame)

# Export data -------------------------------------------------------------
# Save environment to avoid recomputing
save.image(file = "./Environments/compute.RData")
