# Informations ------------------------------------------------------------
# Title: Descriptive_statistics.R
# Author: Félix Boudry
# Contact: <felix.boudry@univ-perp.fr>
# License: GPLv3
# Description: Analyse the data to create descriptive models

# Configuration -----------------------------------------------------------

## Libraries --------------------------------------------------------------
## List of used libraries.
require(tidyverse)
require(factoextra)
require(clusplus)
require(dbscan)

# Environment -------------------------------------------------------------
# Load environment generated by previous script
rm(list = setdiff(x = ls(), y = lsf.str())) # Clean environment
load(file = "./Environments/compute.RData") # Load environment
init_folder(folder_list = c("Output", "Params"))

# Anthropological ---------------------------------------------------------
# Compute anthropological values
antrop_data <- # Summarise descriptive values
  dplyr::summarise(my_data$infos, across(
    .cols = all_of(
      c(
        "age",
        "height",
        "weight",
        "train_years",
        "train_volume",
        "saturation_end"
      )
    ),
    .fns = list(
      \(x) mean = mean(x, na.rm = TRUE),
      \(x) sd = sd(x, na.rm = TRUE)
    )
  )) %>% as.data.frame() %>% round()

# Clustering --------------------------------------------------------------
# Compute and plot clusters
my_counter <- 1
for (analysis_data in lapply(my_data$encoded_summaries, "[[", "encoded_data")) {
  analysis_data <- # Clean and select usable data
    analysis_data %>%
    as.data.frame() %>%
    select_if(is.numeric) %>%
    na.omit() %>%
    select(.data = ., -any_of(c(
      "saturation_rest",
      "saturation_end",
      "saturation_delta"
    )))
  ## Scale data--------------------------------------------------------------
  analysis_data_scaled <-
    scale(x = analysis_data) %>% as.data.frame()

  ## Optimal cluster choice -------------------------------------------------
  cluster_number_graph <-
    optimal_clust(input_data = analysis_data_scaled, cluster_method = kmeans)

  ## Cluster computation ----------------------------------------------------
  ## Compute clusters with different methods
  cluster_number <-
    list(2, 4) # Select number of clusters for analysis
  cluster_number_names <-
    list("two", "four")

  kclust_data <-
    lapply(cluster_number,
           \(x)
           eclust(
             analysis_data,
             k = x,
             FUNcluster = "kmeans",
             graph = FALSE
           )) %>%
    `names<-`(value = cluster_number_names)
  hclust_bu_data <-
    lapply(
      cluster_number,
      \(x)
      eclust(
        analysis_data,
        k = x,
        FUNcluster = "hclust",
        hc_method = "ward.D2",
        graph = FALSE
      )
    ) %>%
    `names<-`(value = cluster_number_names)
  hclust_td_data <-
    lapply(
      cluster_number,
      \(x)
      eclust(
        analysis_data,
        k = x,
        FUNcluster = "diana",
        hc_method = "ward.D2",
        graph = FALSE
      )
    ) %>%
    `names<-`(value = cluster_number_names)
  dbscan_data <-
    dbscan(x = analysis_data_scaled,
           eps = 3,
           minPts = 3)
  optics_data <-
    optics(x = analysis_data_scaled,
           eps = 5,
           minPts = 3)

  ## Plotting ---------------------------------------------------------------
  kclust_graph <-
    lapply(
      kclust_data,
      FUN = function(x) {
        fviz_cluster(object = x,
                     geom = NULL,
                     show.clust.cent = FALSE) +
          {
            if (length(unique(x[["cluster"]])) == 2)
              geom_point(aes(shape = my_data$infos$eih[my_data$keeped_rows %>% as.numeric()]))
          } +
          {
            if (length(unique(x[["cluster"]])) == 4)
              geom_point(aes(shape = my_data$infos$eih[my_data$keeped_rows %>% as.numeric()]))
          } +
          labs(shape = "Status")
      }
    ) %>%
    `names<-`(value = cluster_number_names)
  kclust_coord <-
    lapply(X = kclust_data, FUN = plot_clus_coord, data = analysis_data) %>%
    `names<-`(value = cluster_number_names)
  hclust_bu_graph <- lapply(
    X = hclust_bu_data,
    FUN = function(x) {
      if (length(unique(x[["cluster"]])) == 2)
      {
        my_label_cols <-
          my_data$infos$eih[my_data$keeped_rows %>% as.numeric()] %>% as.factor() %>% as.numeric()
      }
      else if (length(unique(x[["cluster"]])) == 4)
      {
        my_label_cols <-
          my_data$infos$eih_severity[my_data$keeped_rows %>% as.numeric()] %>% as.factor() %>% as.numeric()
      }
      fviz_dend(x = x,
                cex = 0.5,
                label_cols = my_label_cols,
                horiz = TRUE)
    }
  ) %>%
    `names<-`(value = cluster_number_names)
  hclust_td_graph <- lapply(
    X = hclust_td_data,
    FUN = function(x) {
      if (length(unique(x[["cluster"]])) == 2)
      {
        my_label_cols <-
          my_data$infos$eih[my_data$keeped_rows %>% as.numeric()] %>% as.factor() %>% as.numeric()
      }
      else if (length(unique(x[["cluster"]])) == 4)
      {
        my_label_cols <-
          my_data$infos$eih_severity[my_data$keeped_rows %>% as.numeric()] %>% as.factor() %>% as.numeric()
      }
      fviz_dend(x = x,
                cex = 0.5,
                label_cols = my_label_cols,
                horiz = TRUE)
    }
  ) %>%
    `names<-`(value = cluster_number_names)
  dbscan_graph <- fviz_cluster(dbscan_data,
                               analysis_data_scaled,
                               geom = "point",
                               show.clust.cent = FALSE) +
    guides(shape = FALSE)
  optics_graph <-
    extractXi(object = optics_data, xi = 0.02) %>% plot()
  optics_graph <- recordPlot()

  ## Cluster data Structure -----------------------------------------------
  kclust <-
    lst(data = kclust_data,
        coord = kclust_coord,
        graph = kclust_graph)
  hclust_bu <-
    lst(data = hclust_bu_data, graph = hclust_bu_graph)
  hclust_td <-
    lst(data = hclust_td_data, graph = hclust_td_graph)
  dbscan_clust <- lst(data = dbscan_data, graph = dbscan_graph)
  optics_clust <- lst(data = optics_data, graph = optics_graph)

  assign(
    x = paste0("cluster_results_", names(my_data$summaries[my_counter])),
    value = lst(
      cluster_number_graph,
      kclust,
      hclust_bu,
      hclust_td,
      dbscan = dbscan_clust,
      optics = optics_clust
    )
  )
  my_counter <- my_counter + 1
}

# Data structure ----------------------------------------------------------
# Structuring data in vectors
my_results <- lst(antrop = antrop_data)# List results

my_results <- append(x = my_results,
                     values = sapply(
                       X = ls(pattern = "cluster_results.*"),
                       FUN = get,
                       simplify = FALSE,
                       USE.NAMES = TRUE
                     ))

# Remove temporary variables
rm(list = setdiff(x = ls(), y = c(
  lsf.str(), ls(pattern = "my_data|my_results")
)))

# Export data -------------------------------------------------------------
# Save environment to avoid recomputing
save.image(file = "./Environments/descriptive.RData")
