# Informations ------------------------------------------------------------
# Title: Descriptive_statistics.R
# Author: Félix Boudry
# Contact: <felix.boudry@univ-perp.fr>
# License: GPLv3
# Description: Analyse the data to create descriptive models

# Configuration -----------------------------------------------------------

## Libraries --------------------------------------------------------------
## List of used libraries.
require(tidyverse)
require(factoextra)
require(clusplus)
require(dbscan)

# Environment -------------------------------------------------------------
# Load environment generated by previous script
rm(list = setdiff(x = ls(), y = lsf.str())) # Clean environment
load(file = "./Environments/compute.RData") # Load environment

# Anthropological ---------------------------------------------------------
# Compute anthropological values
antrop_data <- # Summarise descriptive values
  dplyr::summarise(my_data$infos, across(
    .cols = all_of(
      c(
        "age",
        "height",
        "weight",
        "train_years",
        "train_volume",
        "saturation_end"
      )
    ),
    .fns = list(
      \(x) mean = mean(x, na.rm = TRUE),
      \(x) sd = sd(x, na.rm = TRUE)
    )
  )) %>% as.data.frame() %>% round()

# Clustering --------------------------------------------------------------
# Compute and plot clusters
my_counter <- 1
for (analysis_data in my_data$summaries) {
  analysis_data <- # Clean and select usable data
    analysis_data %>%
    as.data.frame() %>%
    select_if(is.numeric) %>%
    na.omit() %>%
    select(.data = ., -any_of(c(
      "saturation_rest",
      "saturation_end",
      "saturation_delta"
    )))
  ## Scale data--------------------------------------------------------------
  analysis_data_scaled <-
    scale(x = analysis_data) %>% as.data.frame()

  ## Optimal cluster choice -------------------------------------------------
  cluster_number_graph <-
    optimal_clust(input_data = analysis_data_scaled, cluster_method = kmeans)

  ## Cluster computation ----------------------------------------------------
  ## Compute clusters with different methods
  cluster_number <-
    list(2, 4) # Select number of clusters for analysis
  cluster_number_names <-
    list("two", "four")

  kclust_data <-
    compute_kclust(input = analysis_data_scaled, cluster_number = cluster_number)
  hclust_data <-
    dist(x = analysis_data_scaled) %>% hclust(method = "ward.D2")
  dbscan_data <-
    dbscan(x = analysis_data_scaled,
           eps = 3,
           minPts = 3)
  optics_data <-
    optics(x = analysis_data_scaled,
           eps = 5,
           minPts = 3)

  ## Plotting ---------------------------------------------------------------
  kclust_graph <-
    lapply(X = kclust_data, FUN = fviz_cluster, data = analysis_data) %>%
    `names<-`(value = cluster_number_names)
  kclust_coord <-
    lapply(X = kclust_data, FUN = plot_clus_coord, data = analysis_data) %>%
    `names<-`(value = cluster_number_names)
  hclust_graph <- lapply(X = cluster_number,
                         FUN = hcl_plot,
                         input_data = hclust_data) %>% `names<-`(value = cluster_number_names)
  dbscan_graph <- fviz_cluster(dbscan_data,
                               analysis_data_scaled,
                               geom = "point")
  optics_graph <-
    extractXi(object = optics_data, xi = 0.02) %>% plot() %>% recordPlot()

  ## Boxplots ---------------------------------------------------------------
  ## Boxplot per cluster (absolute data)

  ## Adding cluster group to data
  plot_df <-
    do.call(
      "cbind",
      list(
        analysis_data,
        lapply(X = kclust_data, FUN = "[[", "cluster"),
        lapply(X = cluster_number, function(x)
          cutree(tree = hclust_data, k = x)) %>%
          `names<-`(paste0("hclust_", cluster_number)),
        eih = my_data$summaries$absolute[rownames(analysis_data), "eih"],
        eih_severity = my_data$summaries$absolute[rownames(analysis_data), "eih_severity"]
      )
    )

  ## Creating boxplots
  cluster_columns <- # Select cluster columns
    colnames(x = plot_df[grepl(pattern = "clust", x = colnames(plot_df))])

  # Plotting boxplots for each variable in each cluster
  cluster_boxplots <- lapply(
    X = cluster_columns,
    FUN = function(my_col) {
      sapply(
        X = colnames(plot_df),
        FUN = boxplots_by_clust,
        cluster_col = my_col,
        simplify = FALSE,
        USE.NAMES = TRUE
      )
    }
  ) %>% `names<-`(value = cluster_columns)
  eih_repartition <-
    lapply(
      X = cluster_columns,
      FUN = function(my_col) {
        sapply(
          X = colnames(plot_df["eih"]),
          FUN = subject_repartition,
          cluster_col = my_col,
          simplify = FALSE,
          USE.NAMES = TRUE
        )
      }
    ) %>% `names<-`(value = cluster_columns)
  eih_severity_repartition <-
    lapply(
      X = cluster_columns,
      FUN = function(my_col) {
        sapply(
          X = colnames(plot_df["eih_severity"]),
          FUN = subject_repartition,
          cluster_col = my_col,
          simplify = FALSE,
          USE.NAMES = TRUE
        )
      }
    ) %>% `names<-`(value = cluster_columns)

  ## Cluster data Structure -----------------------------------------------
  kclust <-
    lst(data = kclust_data,
        coord = kclust_coord,
        graph = kclust_graph)
  hclust <- lst(data = hclust_data, hclust_graph)
  dbscan_clust <- lst(data = dbscan_data, graph = dbscan_graph)
  optics_clust <- lst(data = optics_data, graph = optics_graph)

  assign(
    x = paste0("cluster_results_", names(my_data$summaries[my_counter])),
    value = lst(
      cluster_number_graph,
      kclust,
      hclust,
      dbscan = dbscan_clust,
      optics = optics_clust,
      boxplots = cluster_boxplots,
      eih_repartition,
      eih_severity_repartition
    )
  )
  my_counter <- my_counter + 1
}

# Data structure ----------------------------------------------------------
# Structuring data in vectors
my_results <- lst(antrop = antrop_data)# List results

my_results <- append(x = my_results,
                     values = sapply(
                       X = ls(pattern = "cluster_results.*"),
                       FUN = get,
                       simplify = FALSE,
                       USE.NAMES = TRUE
                     ))

# Remove temporary variables
rm(list = setdiff(x = ls(), y = c(
  lsf.str(), ls(pattern = "my_data|my_results")
)))

# Export data -------------------------------------------------------------
# Save environment to avoid recomputing
save.image(file = "./Environments/descriptive.RData")
