# Informations ------------------------------------------------------------

# Title: Descriptive_statistics.R
# Author: Félix Boudry
# Contact: <felix.boudry@univ-perp.fr>
# License: Private
# Description: Analyse the data to create descriptive models

# Configuration -----------------------------------------------------------

## Libraries --------------------------------------------------------------
## List of used libraries.
require(tibble)
require(janitor)
require(dplyr)
require(factoextra)
require(clusplus)
require(data.table)
require(dbscan)
require(fpc)
require(FCPS)

# Environment -------------------------------------------------------------
# Load environment generated by previous script
rm(list = ls()) # Clean environment
load(file = "./Environments/compute.RData") # Load environment

# Descriptive values ------------------------------------------------------
my_measures <- # List descriptive values
  c("age",
    "height",
    "weight",
    "train_years",
    "train_volume")

antrop_data <- # Summarise descriptive values
  dplyr::summarise(my_data$infos, across(
    .cols = all_of(my_measures),
    # Use all columns selected
    .fns = list(mean = mean, sd = sd),
    # Apply functions
    na.rm = TRUE
  )) %>% cbind(saturation_mean = mean(x = my_data$infos$saturation_end, na.rm = TRUE)) %>%
  cbind(saturation_sd = sd(x = my_data$infos$saturation_end, na.rm = TRUE)) %>%
  round()

# Clustering --------------------------------------------------------------
# Prepare data for clustering

## Data selection ---------------------------------------------------------
## Select data used for the cluster analysis
analysis_data_absolute <- my_data$summary %>%
  select_if(is.numeric) %>% # Select only numeric data
  na.omit() # Remove NA's
analysis_data_relative <- my_data$summary_relative %>%
  select_if(is.numeric) %>% # Select only numeric data
  na.omit() # Remove NA's

my_analysis_data <-
  lst(analysis_data_absolute, analysis_data_relative) %>%
  `names<-`(c("absolute", "relative"))

my_counter <- 1
for (data_to_analyze in my_analysis_data) {
  # Loop analyzing data in "my_analysis_data"
  analysis_data <- data_to_analyze
  ## Scale data--------------------------------------------------------------
  ## Format data for clustering (scaling)
  analysis_data_scaled <- scale(x = analysis_data) %>%
    as.data.frame(x = .)

  ## Cluster number computation ---------------------------------------------
  ## Choose number of cluster for analysis
  elbow_graph <-
    fviz_nbclust(analysis_data_scaled, kmeans, method = "wss") +
    geom_vline(xintercept = 2, linetype = 2) +
    labs(subtitle = "Elbow method") +
    ggtitle(label = "Optimal number of cluster")
  silhouette_graph <-
    fviz_nbclust(analysis_data_scaled, kmeans, method = "silhouette") +
    labs(subtitle = "Silhouette method") +
    ggtitle(label = "Optimal number of cluster")
  gap_graph <-
    fviz_nbclust(
      analysis_data_scaled,
      kmeans,
      nstart = 25,
      method = "gap_stat",
      nboot = 50
    ) +
    labs(subtitle = "Gap statistic method") +
    ggtitle(label = "Optimal number of cluster")

  cluster_number_graph <- # Put graphs in list
    lst(elbow_graph, silhouette_graph, gap_graph)
  names(x = cluster_number_graph) <- c("elbow", "silhouette", "gap")
  rm(elbow_graph, silhouette_graph, gap_graph)

  ## Cluster computation ----------------------------------------------------
  ## Compute clusters with different methods
  cluster_number <-
    list(2, 4) # Select number of clusters for analysis
  ### K-Means ---------------------------------------------------------------
  ### Compute cluster data
  for (i in cluster_number) {
    # Compute kmeans cluster for cluster numbers in "cluster_number"
    assign(x = paste0("kclust_", i),
           value = kmeans(analysis_data_scaled, i))
  }

  data_kclust <- # Put generated clusters in a list
    lapply(X = ls(pattern = "kclust_"), FUN = get)
  names(x = data_kclust) <-
    ls(pattern = "kclust_") # Renaming list clusters

  ### Hierarchical ----------------------------------------------------------
  hierar_distance <-
    # Compute data distance for hierarchical cluster
    dist(x = analysis_data_scaled, method = "euclidian")
  hierar_cluster_data <-
    hclust(d = hierar_distance, method = "ward.D2") # Compute clusters

  for (i in cluster_number) {
    assign(x = paste0("hierar_clust_", i),
           value = cutree(hierar_cluster_data, i)) # Create a tree
  }

  data_hierar_clust <-
    lapply(X = ls(pattern = "hierar_clust_"), FUN = get)
  names(x = data_hierar_clust) <- ls(pattern = "hierar_clust_")

  ### DBSCAN ----------------------------------------------------------------
  dbscan_clust <-
    fpc::dbscan(analysis_data_scaled, eps = 3, MinPts = 3)
  data_dbscan <- # Put generated clusters in a list
    lapply(X = ls(pattern = "dbscan_clust"), FUN = get)
  names(x = data_dbscan) <-
    ls(pattern = "dbscan_clust") # Renaming list clusters

  ### OPTICS ----------------------------------------------------------------
  optics_clust <-
    OPTICSclustering(analysis_data_scaled,
                     MaxRadius = 5,
                     RadiusThreshold = 3)
  data_optics <- # Put generated clusters in a list
    lapply(X = ls(pattern = "optics_clust"), FUN = get)
  names(x = data_optics) <-
    ls(pattern = "optics_clust") # Renaming list clusters

  ## Plotting ---------------------------------------------------------------

  ### K-Means ---------------------------------------------------------------
  ### Plotting k-means clusters
  my_count <- 1
  for (i in data_kclust) {
    # For each cluster print a graph
    assign(
      x = paste0(names(data_kclust[my_count]), "_graph"),
      value = fviz_cluster(object = i, data = analysis_data)
    ) # Print cluster graph
    assign(
      x = paste0(names(data_kclust[my_count]), "_coord"),
      value = plot_clus_coord(cluster_model = i, data = analysis_data)
    ) # Print coordinates graph
    my_count <- my_count + 1
  }

  kclust_graph <-
    lapply(X = ls(pattern = "kclust_.*_graph"), FUN = get)
  kclust_coord <-
    lapply(X = ls(pattern = "kclust_.*_coord"), FUN = get)

  ### Hierarchical ----------------------------------------------------------
  ### Plotting hierarchical clusters
  for (i in cluster_number) {
    # For each cluster print a graph
    plot(x = hierar_cluster_data, cex = 0.6)
    rect.hclust(tree = hierar_cluster_data, k = i) # Print box to separate clusters
    assign(x = paste0("hierar_clust_graph", i),
           value = recordPlot())
  }

  hierar_graph <-
    lapply(X = ls(pattern = "hierar_clust_graph.*"),
           FUN = get)

  ### DBSCAN ----------------------------------------------------------------
  dbscan_graph <- fviz_cluster(
    data_dbscan$dbscan_clust,
    analysis_data_scaled,
    stand = FALSE,
    ellipse = TRUE,
    geom = "point"
  )
  assign(x = paste0("dbscan_clust_graph", i),
         value = dbscan_graph)

  dbscan_graph <-
    lapply(X = ls(pattern = "dbscan_clust_graph.*"),
           FUN = get)

  ### OPTICS ----------------------------------------------------------------
  plot(optics_clust$Object)
  optics_graph <- recordPlot()
  assign(x = paste0("optics_clust_graph", i),
         value = optics_graph)

  optics_graph <-
    lapply(X = ls(pattern = "optics_clust_graph.*"),
           FUN = get)

  ### Boxplots --------------------------------------------------------------
  ### Boxplot per cluster (absolute data)

  ## Adding cluster group to data
  my_count <- 1
  for (i in data_kclust) {
    analysis_data[, names(data_kclust[my_count])] <- # Select subject
      as.character(x = i[["cluster"]]) # Add cluster information
    my_count <- my_count + 1
  }
  my_count <- 1
  for (i in data_hierar_clust) {
    analysis_data[, names(data_hierar_clust[my_count])] <-
      # Select subject
      as.character(x = i) # Add cluster information
    my_count <- my_count + 1
  }

  plot_df <-
    as.data.frame(x = analysis_data) %>% # Copy dataframe and add informations
    cbind(eih = my_data$labels[, "eih"][match(x = rownames(analysis_data),
                                              table = rownames(my_data$labels))]) %>%
    cbind(eih_severity = my_data$labels[, "eih_severity"][match(x = rownames(analysis_data),
                                                                table = rownames(my_data$labels))])

  ## Creating boxplots
  cluster_columns <- # Select cluster columns
    colnames(x = plot_df[grepl(pattern = "clust", x = colnames(plot_df))])

  # PLotting boxplots for each variable in each cluster
  do_plot <- function(data_col) {
    # Function to plot boxplots
    ggplot(plot_df, aes(x = !!sym(cluster_col), y = !!sym(paste(data_col)))) +
      geom_boxplot(aes(
        group = !!sym(cluster_col),
        fill = !!sym(cluster_col)
      )) +
      ggtitle(label = paste(data_col, "par cluster"))
  }

  for (cluster_col in cluster_columns) {
    # Apply do_plot for different cluster numbers
    assign(x = paste0(cluster_col, "_boxplot"),
           value = lst())
    assign(
      x =
        paste0(cluster_col, "_boxplot"),
      value = sapply(
        # Make a plot for each column
        colnames(x = plot_df),
        FUN = do_plot,
        simplify = FALSE,
        USE.NAMES = TRUE
      )
    )
  }
  # PLotting eih subject repartition
  do_plot <- function(data_col) {
    ggplot(data = plot_df, mapping = aes(x = !!(1:nrow(x = plot_df)),
                                         y = !!sym(paste(data_col)))) +
      geom_point(mapping = aes(color = !!sym(paste(cluster_col)))) +
      ggtitle(label = "Subject repartition in clusters")
  }

  for (cluster_col in cluster_columns) {
    assign(x = paste0(cluster_col, "_eih_repart"),
           value = lst())
    assign(
      x =
        paste0(cluster_col, "_eih_repart"),
      value = sapply(
        colnames(x = plot_df["eih"]),
        FUN = do_plot,
        simplify = FALSE,
        USE.NAMES = TRUE
      )
    )
  }
  # Plotting eih severity repartition
  for (cluster_col in cluster_columns) {
    assign(x = paste0(cluster_col, "_eih_repart_severity"),
           value = lst())
    assign(
      x =
        paste0(cluster_col, "_eih_repart_severity"),
      value = sapply(
        colnames(plot_df["eih_severity"]),
        FUN = do_plot,
        simplify = FALSE,
        USE.NAMES = TRUE
      )
    )
  }

  cluster_boxplots <- # List boxplots
    sapply(
      X = ls(pattern = ".*boxplot"),
      FUN = get,
      simplify = FALSE,
      USE.NAMES = TRUE
    )
  subject_repartition <- # List subject repartition
    sapply(
      X = ls(pattern = ".*_eih_repart.*"),
      FUN = get,
      simplify = FALSE,
      USE.NAMES = TRUE
    )

  ## Cluster data Structure -----------------------------------------------
  kclust <- lst(data_kclust, kclust_coord, kclust_graph)
  hierar_clust <- lst(data_hierar_clust, hierar_graph)
  dbscan_clust <- lst(data_dbscan, dbscan_graph)
  optics_clust <- lst(data_optics, optics_graph)

  assign(
    x = paste0("cluster_results_", names(my_analysis_data[my_counter])),
    value = lst(
      cluster_number_graph,
      kclust,
      hierar_clust,
      dbscan_clust,
      optics_clust,
      cluster_boxplots,
      subject_repartition
    )
  )
  my_counter <- my_counter + 1

  # Remove temporary variables
  rm(list = setdiff(
    ls(),
    ls(pattern = "my_data|my_results|my_analysis_data|analysis.*|my_counter|cluster_results.*|.*antrop.*")
  ))
}

# Data structure ----------------------------------------------------------
# Structuring data in vectors
my_results <- lst(antrop = antrop_data)# List results

my_results <- append(x = my_results,
                     values = sapply(
                       X = ls(pattern = "cluster.*"),
                       FUN = get,
                       simplify = FALSE,
                       USE.NAMES = TRUE
                     ))

# Remove temporary variables
rm(list = setdiff(x = ls(), y = ls(pattern = "my_data|my_results")))

# Export data -------------------------------------------------------------
# Save environment to avoid recomputing
save.image(file = "./Environments/descriptive.RData")
